services:
  database:
    image: 'postgres:16.1-alpine3.19'
    env_file:
      - ../.env
    ports:
      - '5432:5432'
  mailcatcher:
    container_name: mailcatcher
    image: sj26/mailcatcher
    expose:
      - 1025
      - 1080
    ports:
      - 1025:1025 #email smtp port
      - 1080:1080 #email http port

